# Site settings
title: GreyCat
email: evillove2304@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Page where i share all the thing i have learn
baseurl: "https://bibjby.github.io" 
url: "http://bibjby.github.io" # the base hostname & protocol for your site
twitter_username: none
github_username:  bibjby
GoogleAnalytics: UA-xxxxxx-x

twitter:
  username: none
facebook:
  app_id: none
  publisher: none

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'
